-- Table : app_user
CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    role VARCHAR(50),
    locked BOOLEAN,
    enabled BOOLEAN
);

-- Table : livreurs
CREATE TABLE livreurs (
    id BIGINT PRIMARY KEY,
    phone_number VARCHAR(20),
    is_active BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_livreur_user FOREIGN KEY (id) REFERENCES app_user(id) ON DELETE CASCADE
);


-- Table : clients
CREATE TABLE clients (
    id BIGINT PRIMARY KEY,
    address VARCHAR(255),
    CONSTRAINT fk_client_user FOREIGN KEY (id) REFERENCES app_user(id) ON DELETE CASCADE
);
CREATE TABLE admin (
 id BIGINT PRIMARY KEY,
 telephone VARCHAR(20),
 CONSTRAINT fk_admin_user FOREIGN KEY (id) REFERENCES app_user(id) ON DELETE CASCADE
);

-- Table: produits
CREATE TABLE produits (
  id VARCHAR(36) PRIMARY KEY,
  nom VARCHAR(255),
  prix_unitaire DOUBLE,
  stock INT,
  description VARCHAR(255),
  type VARCHAR(255),
  image VARCHAR(255)
);

/*
-- Remplacer l'instruction problématique
ALTER TABLE produits ALTER COLUMN nom VARCHAR(255) NOT NULL;
ALTER TABLE produits ALTER COLUMN prix_unitaire DOUBLE NOT NULL;
ALTER TABLE produits ALTER COLUMN stock INT NOT NULL;
ALTER TABLE produits ALTER COLUMN stock SET DEFAULT 0;*/


-- Table: orders
CREATE TABLE orders (
    id VARCHAR(255) PRIMARY KEY,
    client_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL DEFAULT 'EN_ATTENTE' CHECK (status IN ('EN_ATTENTE', 'EN_COURS', 'LIVREE', 'ANNULEE')) ,
    delivery_address TEXT,
    scheduled_for TIMESTAMP,
    delivered_at TIMESTAMP,
    note TEXT,
    total_amount DOUBLE,

    CONSTRAINT fk_orders_client FOREIGN KEY (client_id) REFERENCES clients(id)
);
/*
-- Remplacer l'instruction Order
ALTER TABLE orders ALTER COLUMN id RESTART WITH (SELECT MAX(id) + 1 FROM orders);
ALTER TABLE orders ALTER COLUMN status VARCHAR(50) NOT NULL;
ALTER TABLE orders ALTER COLUMN total_amount SET DATA TYPE DOUBLE;
ALTER TABLE orders ALTER COLUMN total_amount SET NOT NULL;
ALTER TABLE orders ALTER COLUMN total_amount SET DEFAULT 0.0;*/


CREATE TABLE order_item (
    id VARCHAR(255) PRIMARY KEY,
    order_id VARCHAR(255) NOT NULL,
    produit_id VARCHAR(36) NOT NULL,
    quantity DOUBLE,
    unit_price DOUBLE,
    subtotal DOUBLE,
    note TEXT,

    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_item_produit FOREIGN KEY (produit_id) REFERENCES produits(id) ON DELETE CASCADE
);
/*
-- Remplacer l'instruction problématique ORDER_ITEM
ALTER TABLE order_item ALTER COLUMN id RESTART WITH (SELECT MAX(id) + 1 FROM order_item);
ALTER TABLE order_item ALTER COLUMN quantity DOUBLE NOT NULL;
ALTER TABLE order_item ALTER COLUMN unit_price DOUBLE NOT NULL;
ALTER TABLE order_item ALTER COLUMN subtotal DOUBLE NOT NULL;*/

-- Table: reclamations
CREATE TABLE reclamations (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    client_id BIGINT NOT NULL,
    order_id VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    type VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    resolution_notes TEXT,
    file_path VARCHAR(255),
    FOREIGN KEY (client_id) REFERENCES clients(id),
    FOREIGN KEY (order_id) REFERENCES orders(id)

);

-- Table: livraisons
CREATE TABLE livraisons (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    order_id VARCHAR(255) NOT NULL,
    livreur_id BIGINT NOT NULL,
    scheduled_time TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'SCHEDULED' CHECK (status IN ('SCHEDULED', 'IN_PROGRESS', 'DELIVERED', 'CANCELLED')),
    delivery_address VARCHAR(255) NOT NULL,
    notes TEXT,
    delivered_at TIMESTAMP,
    tracking_code VARCHAR(255) UNIQUE,
    latitude DOUBLE,
    longitude DOUBLE,
    is_urgent BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_livraisons_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_livraisons_livreur FOREIGN KEY (livreur_id) REFERENCES livreurs(id)
);
/*
-- Ajustements pour livraisons
ALTER TABLE livraisons ALTER COLUMN id RESTART WITH (SELECT MAX(id) + 1 FROM livraisons);
ALTER TABLE livraisons ALTER COLUMN status SET NOT NULL;
ALTER TABLE livraisons ALTER COLUMN delivery_address SET NOT NULL;
ALTER TABLE livraisons ALTER COLUMN is_urgent SET DEFAULT FALSE;*/



