-- Table : app_user
CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    role VARCHAR(50),
    locked BOOLEAN,
    enabled BOOLEAN
);

-- Table : livreurs
CREATE TABLE livreurs (
    id BIGINT PRIMARY KEY,
    phone_number VARCHAR(20),
    is_active BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_livreur_user FOREIGN KEY (id) REFERENCES app_user(id) ON DELETE CASCADE
);


-- Table : clients
CREATE TABLE clients (
    id BIGINT PRIMARY KEY,
    address VARCHAR(255),
    CONSTRAINT fk_client_user FOREIGN KEY (id) REFERENCES app_user(id) ON DELETE CASCADE
);

-- Table: produits
CREATE TABLE produits (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(255),
  prix_unitaire DOUBLE,
  stock INT
);

-- Table: orders
CREATE TABLE orders (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    client_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50),
    delivery_address TEXT,
    scheduled_for TIMESTAMP,
    delivered_at TIMESTAMP,
    note TEXT,
    total_amount DOUBLE,

    CONSTRAINT fk_orders_client FOREIGN KEY (client_id) REFERENCES clients(id)
);

-- Table: order_item
CREATE TABLE order_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    order_id BIGINT NOT NULL,
    produit_id BIGINT NOT NULL,
    quantity DOUBLE,
    unit_price DOUBLE,
    subtotal DOUBLE,
    note TEXT,

    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_item_produit FOREIGN KEY (produit_id) REFERENCES produits(id)
);

