package ma.akwa.portalrh.commande.mapper;

import ma.akwa.portalrh.commande.dto.OrderRequestDTO;
import ma.akwa.portalrh.commande.dto.OrderResponseDTO;
import ma.akwa.portalrh.commande.entities.Order;
import ma.akwa.portalrh.commande.entities.OrderItem;
import ma.akwa.portalrh.produit.entities.Produit;
import ma.akwa.portalrh.produit.mapper.ProduitMapper;
import org.mapstruct.*;

import java.util.List;

@Mapper(componentModel = "spring", uses = {ProduitMapper.class})
public interface OrderMapper {

    // Map from OrderRequestDTO to Order entity
    @Mapping(target = "id", ignore = true)  // id usually autogenerated
    @Mapping(target = "client", ignore = true) // client mapping done elsewhere or set manually
    @Mapping(target = "createdAt", expression = "java(java.time.LocalDateTime.now())")
    @Mapping(target = "status", ignore = true)  // status set elsewhere
    @Mapping(target = "deliveryAddress", ignore = true) // set elsewhere
    @Mapping(target = "scheduledFor", ignore = true) // set elsewhere
    @Mapping(target = "deliveredAt", ignore = true) // set elsewhere
    @Mapping(target = "note", ignore = true)
    @Mapping(target = "totalAmount", ignore = true)
    @Mapping(source = "items", target = "items")
    Order toOrder(OrderRequestDTO dto);

    // Map list of OrderLineDTO to list of OrderItem (partial mapping)
    List<OrderItem> mapOrderLines(List<OrderRequestDTO.OrderLineDTO> orderLines);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "order", ignore = true)  // set parent order in service layer
    @Mapping(target = "produit", source = "productId", qualifiedByName = "mapProductIdToProduit")
    @Mapping(target = "quantity", source = "quantity")
    @Mapping(target = "unitPrice", ignore = true)
    @Mapping(target = "subtotal", ignore = true)
    @Mapping(target = "note", ignore = true)
    OrderItem toOrderItem(OrderRequestDTO.OrderLineDTO orderLineDTO);

    // Map from Order entity to OrderResponseDTO
    @Mapping(source = "status", target = "status", qualifiedByName = "orderStatusToString")
    @Mapping(source = "items", target = "items")
    OrderResponseDTO toOrderResponseDTO(Order order);

    // Map list of OrderItem to list of OrderLineDTO
    List<OrderResponseDTO.OrderLineDTO> mapOrderItemsToOrderLineDTOs(List<OrderItem> items);

    @Mapping(source = "produit.id", target = "productId")
    @Mapping(source = "quantity", target = "quantity")
    OrderResponseDTO.OrderLineDTO toOrderLineDTO(OrderItem orderItem);

    // Custom mapping for productId -> Produit entity (simplified: only sets id)
    @Named("mapProductIdToProduit")
    default Produit mapProductIdToProduit(Long productId) {
        if (productId == null) {
            return null;
        }
        Produit produit = new Produit();
        produit.setId(productId);
        return produit;
    }

    @Named("orderStatusToString")
    default String orderStatusToString(Enum<?> status) {
        return status == null ? null : status.name();
    }
}
